# Change these first
owner: timedin-de # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: timedin.net
    url: https://www.timedin.net
    icon: https://static.timedin.net/icons/android-icon-192x192.png
  - name: api.timedin.net
    url: https://www.timedin.net
    icon: https://static.timedin.net/icons/android-icon-192x192.png
  - name: 2t0.de
    icon: https://static.timedin.net/icons/android-icon-192x192.png
    url: https://2t0.de/
  - name: mail.timedin.net (SMTP-TLS)
    icon: https://static.timedin.net/icons/android-icon-192x192.png
    url: mail.timedin.net
    port: 587
    check: "tcp-ping"
  - name: mail.timedin.net (MX)
    icon: https://static.timedin.net/icons/android-icon-192x192.png
    url: mail.timedin.net
    port: 25
    check: "tcp-ping"
 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.timedin.net
  #baseUrl: /upptime
  customHeadHtml: "<meta name=\"robots\" content=\"noarchive noimageindex\">"
  
  logoUrl: https://static.timedin.net/img/timedin-logo.svg
  favicon: https://static.timedin.net/icons/android-icon-192x192.png
  faviconSvg: https://static.timedin.net/img/timedin-logo.svg
  
  name: Status Page | TimedIn
  introTitle: "**TimedIn**: simple, free and open services."
  introMessage: Our status page shows the response- and uptime of all our services and systems.
  navbar:
    - title: TimedIn.net
      href: https://www.timedin.net/
    - title: NoCookies.net
      href: https://www.no-cookies.net
i18n:
  footer: ""